version: 0.0
os: linux
files:
  - source: gameoflife-web/target/gameoflife.war
    destination: /tmp/gameoflife.war
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
