version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Downloading Maven 3.6.3...
      - curl -sL -o /tmp/maven.tar.gz https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.tar.gz && tar xzf /tmp/maven.tar.gz -C /tmp
      - export M2_HOME=/tmp/apache-maven-3.6.3
      - export PATH=$M2_HOME/bin:$PATH
      - mvn clean install -DskipTests
      - aws s3 ls 
      - aws s3 ls s3://artifacts-mumbai/
      - cd gameoflife-web/target && ls -ltr

  build:
    commands:
      - echo Building WAR file...
      - echo Building Docker image...

  post_build:
    commands:
      - echo Listing WAR file to verify build...
      - echo Uploading WAR file to S3 bucket...

artifacts:
  files:
    - gameoflife-web/target/gameoflife.war

